### ISSUE TITLE
Feature Request: Have clicking Configure Game Settings button Default to Module Settings tab

### ISSUE THREAD

**Issue by Norc** [sdenec/tidy-ui_game-settings#11]
I click the "Configure Settings" button many many times a day, and virtually every time I then immediately click to the Module Settings. As a user with many modules that I'm constantly testing, I'd like to be able to have the Module Settings tab be selected by default.

Not sure if it's worth adding a setting to toggle this behavior or not, but it would probably be a good idea in case some users did not want this behavior. Possibly even off by default.

Priority: Low

**Comment by sdenec** [comment]
Option added :)
