### ISSUE TITLE
Export of plugins lacks version and is not human readable

### ISSUE THREAD

**Issue by apoapostolov** [sdenec/tidy-ui_game-settings#15]
The list of activated modules is not very readable as a single semicolon-delimited list. It also lacks the version for each module which I think is very important for spotting conflicts.

**Comment by sdenec** [comment]
The intend was to export a quick list of module names to be able to quickly restore active modules - for example without backing up a whole world. But I changed the output a little - added lines breaks and version number. That's all this simple mod can acomplish right now.

**Comment by apoapostolov** [comment]
That is extremely useful for the purpose of avoiding to the backup whole world to retain mod setup when hunting what mod A causes conflict with mod B. I wasn't aware that was the initial goal, I thought it was for sharing to devs what mods you have on so they can resolve issues. This totally makes sense now, and thanks for making it somewhat human-readable - all good.
