### ISSUE TITLE
Reverse button order or hide Deactivate All Modules

### ISSUE THREAD

**Issue by apoapostolov** [sdenec/tidy-ui_game-settings#26]
Foundry uses a weird scheme for placing positive and negative buttons in order of positive on left and negative on the right, and in this case of Module Settings it is too easy to click on Deactivate All Modules and wreck a whole world because all mods just got removed. An option to reverse order or to hide this button would be much appreciated.

**Comment by sdenec** [comment]
In 0.1.18 I've added a setting to disable the "Deactivate All Modules" Button at the bottom of the Modules Management window. The "uncheck all" Button added by the module is still available at the top. I hope that makes "accidents" less likely to happen!
