### ISSUE TITLE
Layout of 0.1.16 is all out of whack... 

### ISSUE THREAD

**Issue by Silvestrae** [sdenec/tidy-ui_game-settings#28]
When using 0.6.5, check boxes for modules over top text, toggle info button gone, overall harder to read and use.
0.6.6 should be made a package requirement for update

**Comment by sdenec** [comment]
The yesterday released 0.1.17 fixes the layout problems for 0.6.5. Except for the search function and toggle info button which was integrated into 0.6.6. It required the latest version but I was asked to make it compatible with earlier version. That was the compromise. Long story short: use 0.6.6 for best experience but it will work with earlier version minus some comfort features.
