### ISSUE TITLE
Module management window display issue

### ISSUE THREAD

**Issue by bnp800** [sdenec/tidy-ui_game-settings#29]
![image](https://user-images.githubusercontent.com/69395973/91292031-9fcbbd00-e79e-11ea-87c4-50a8db33af57.png)

**Comment by sdenec** [comment]
It seems you are using foundry 0.6.5? Make sure that you have tidy ui 0.1.17 installed.

**Comment by bnp800** [comment]
> It seems you are using foundry 0.6.5? Make sure that you have tidy ui 0.1.17 installed.

Yes, core version 0.6.5, tidy ui 0.1.17

After the latest update this issue occurred.

**Comment by sdenec** [comment]
Then I suspect a module conflict. Maybe with the "find the culprit" mod? But I will take a look and it. Problem is that the document structure is different in 0.6.5 and 0.6.6 and it's difficult to make it fit for both cases. Anyway thanks for the report!

**Comment by bnp800** [comment]
> Then I suspect a module conflict. Maybe with the "find the culprit" mod? But I will take a look and it. Problem is that the document structure is different in 0.6.5 and 0.6.6 and it's difficult to make it fit for both cases. Anyway thanks for the report!

I disabled all modules but tidy ui, nothing changed.

**Comment by sdenec** [comment]
Found the problem. I have my own separate tidy ui theme for foundry and that made it look good! I'll try to fix it when I have the time! Thanks for testing.

**Comment by sdenec** [comment]
0.6.6 is now a stable release. I've fixed the display error in 0.6.5 aswell but this should no longer be an issue with module version 0.1.18!
