### ISSUE TITLE
[Feature request] Add multilanguage support

### ISSUE THREAD

**Issue by lozalojo** [sdenec/tidy-ui_game-settings#32]
Please add the framework for translating the module to other languages (as other modules do, with an en.json file in a lang folder with keys that we can translate).

I have translated more than 10 modules and this one doesnt support translating.

Thanks and great work!

**Comment by sdenec** [comment]
Language Support added!

**Comment by lozalojo** [comment]
Great, sent you a MR, BTW, there is something missing yet, could it be added?

![](https://i.ibb.co/9pQ82LV/screenshot-79.jpg)

**Comment by sdenec** [comment]
oh, yeah, forgot about that. I will add it as soon as possible!

**Comment by lozalojo** [comment]
Please, notify me when its added, I will update the translation file

**Comment by sdenec** [comment]
I have updated the translation strings. Please make your changes in the 0.1.20 branch so i can push a single update with the complete spanish translation :)

**Comment by lozalojo** [comment]
Done! take a look at the PR, added new strings.

**Comment by sdenec** [comment]
Thanks for the spellcheck. Pushed the update :)
