### ISSUE TITLE
More compact "Manage Modules" screen

### ISSUE THREAD

**Issue by M0nk3yy** [sdenec/tidy-ui_game-settings#37]
Suggestion:

Core has been updated with a more compact Manage Modules page. Whilst originally Tidy5e was the more compact option, it now takes up more space than the default. I think greater information density is useful in this case (mid-heavy module user).

**Comment by sdenec** [comment]
Hi. Can you give me a screenshot example of what you are refering to? I don't see any changes in the core Module Manager or in Tidy5e Games Settings respectively.

**Comment by sdenec** [comment]
Original Module Manager
![original_mm](https://user-images.githubusercontent.com/8881200/96844923-64710600-1450-11eb-8299-49bc8d964db8.jpg)

Tidy5e Module Manager
![tidy_mm](https://user-images.githubusercontent.com/8881200/96845012-81a5d480-1450-11eb-9073-3938db68e0f8.jpg)

**Comment by sdenec** [comment]
ah, sorry. forget that. I had my own Theme active that seems to interact with the module manager css. I'll see when I get to make some adjustments!

**Comment by sdenec** [comment]
Okay, it was quite an easy fix that I could do at once. Should be more compact like the core version now!
