### ISSUE TITLE
Weird spacing for icons on buttons on the 'Configure Game Settings' form

### ISSUE THREAD

**Issue by bluesatin** [sdenec/tidy-ui_game-settings#41]
## Issue
On buttons that have icons within the 'Configure Game Settings' form, there are rather large and weird looking gaps between the icon and the actual button text.

| Screenshot |
| ------------ |
| ![Screenshot](https://user-images.githubusercontent.com/5046245/105628581-a174dc00-5e35-11eb-9a2b-b54959a6fee8.png) |

## Cause
This seems to be caused by the label selector + style starting on [line:127](https://github.com/sdenec/tidy-ui_game-settings/blob/fbd46d50bbde9d99b9165bc6688ead52c8e0244a/styles/tidy-ui_game-settings.css#L127) in the CSS file, that appears to be designed for the labels above the buttons but is also applying to the label within buttons; causing the rather large gap between the icon and text on buttons.

## Discussion
Adding in an unset to the margins on labels within buttons seems to be the easiest way to fix the gap without touching anything else, like trying to make the label selector that adds the margin more specific.

Something like:

```
#client-settings section.content .submenu button label {
    margin: unset;
}
```

----

Thanks for the module, makes dealing with module-settings so much easier! :)

**Comment by sdenec** [comment]
Never noticed this. Well, it's partly because of the strange markup with labels inside buttons. But yeah, your fix will work.
It's nothing mod breaking though and doesn't require an immediate update. Anyway, I'll keep it in mind!

**Comment by sdenec** [comment]
Finally got around to remove the spacing^^
