### ISSUE TITLE
Cannot manually edit number of available hit dice

### ISSUE THREAD

**Issue by dstein766** [sdenec/tidy-ui_game-settings#42]
FVTT 0.7.9
DND5e 1.2.4
Tidy5e 0.4.13

As a GM, I cannot figure out any way to manually edit # of (available) Hit Dice on a PC's sheet.  In earlier versions I could do this.  In more recent versions I cannot figure out where this function exists (or IF it still exists).
ACTION: Move cursor to hover over HD in lower right of portrait.  
![image](https://user-images.githubusercontent.com/24942951/106783555-46df3b00-6600-11eb-9526-435862915836.png)

EXPECTED: One of either left-click or right-click will turn pointer into edit bar and allow me to manually enter a value of the HD box.
ACTUAL: Nothing happens

Here are my full list of settings, in case relevant.
![image](https://user-images.githubusercontent.com/24942951/106783404-23b48b80-6600-11eb-9e40-01631d6c2e5d.png)
![image](https://user-images.githubusercontent.com/24942951/106783424-2adb9980-6600-11eb-9dd3-e7ed7694b38a.png)
![image](https://user-images.githubusercontent.com/24942951/106783476-34650180-6600-11eb-8c9e-9a7232cc49ad.png)
![image](https://user-images.githubusercontent.com/24942951/106783507-3b8c0f80-6600-11eb-9267-fc5526074b9b.png)

**Comment by sdenec** [comment]
Hi, you can't manually edit HD and to my knowledge you never could as they are derived from the character's level. 100 % not in my sheet and pretty certain not in the default sheet.

**Comment by sdenec** [comment]
also: wrong module^^

**Comment by dstein766** [comment]
Oops - sorry about that.  Clicked the wrong link in my modules list.

My ref wasn't to max HD, but rather current (available) HD.  The use 
case here is that I have one player who manually tracks this value and 
asked if I could update his character sheet to reflect that he still had 
1 (of 3) HD still available for use and (later, following a long rest) 
now had 2 of 3 available.

However, I accept that mod of this field may not be supported and that 
my memory of doing so is likely to be faulty!

------ Original Message ------
