### ISSUE TITLE
Amibient sounds require a refresh for volume changes to take effect

### ISSUE THREAD

**Issue by Avitale34** [sdenec/tidy-ui_game-settings#45]
I did some testing and tracked it down to this module. Whenever it is installed I have to do a full refresh to get ambient sounds volumes to change. When this module is off the update instantly.

**Comment by sdenec** [comment]
Yeah, that would be very strange if tidy UI would affect the settings itself as only css is affected by the module and its scripts. Pretty sure it is something else!
