### ISSUE TITLE
Keep search bar docked on top (maybe as a module setting)

### ISSUE THREAD

**Issue by ccjmk** [sdenec/tidy-ui_game-settings#46]
When you have enough modules or you open up one, the search bar is easily hidden on top. It would be mighty useful to keep it docked on top so you can always search for another module!

![image](https://user-images.githubusercontent.com/4467128/117292567-47d67180-ae68-11eb-891f-1fb4004b32c2.png)

**Comment by sdenec** [comment]
Search bar should now stay in sight! Good usability advise :)

**Comment by ccjmk** [comment]
wonderful! For some future update when you have some other small thing to add, I would consider adding a setting for the searchbar docking on the module settings, I guess some people might prefer it to not dock (smaller screens, people who use some other modules to play on tablets/phones, etc) and if I'm not missing any obvious detail, it should just be some conditional CSS class based on a module property. Again, absolutely not a priority, but someone will probably appreciate it!
