### ISSUE TITLE
[WFRP4e] the settings dialog dont use the whole height

### ISSUE THREAD

**Issue by mcailleaux** [sdenec/tidy-ui_game-settings#48]
Hi, for WFRP4e, the settings dialog dont use the whole height

![image](https://user-images.githubusercontent.com/18030833/117546440-bd8a3b00-b02a-11eb-9783-e2606df14d0b.png)

It can be fixed by adding/forcing max-height: 100% to the form and his section elements (see capture)

![HotfixCSS](https://user-images.githubusercontent.com/18030833/117546722-1ad2bc00-b02c-11eb-84d6-9775de92291e.png)

**Comment by sdenec** [comment]
Hi, I don't maintain any styles for Warhammer. I think someone else has created some form of support for my module. Currently I only have written styles for the dnd5e system. Maybe the warhammer dev himself?

**Comment by sdenec** [comment]
Actually those styles are entirely regulated by the warhammer stylesheet. So you might be better off addressing the issue to them.
