### ISSUE TITLE
[WFRP4e] checkbox margin to short

### ISSUE THREAD

**Issue by mcailleaux** [sdenec/tidy-ui_game-settings#49]
On the settings dialog, the margin between checkbox and label is to short

![image](https://user-images.githubusercontent.com/18030833/117546786-7dc45300-b02c-11eb-95de-7aaa8aeac6d3.png)

It can be fixed by changing : 

margin: 0 0 .25rem calc(13px + 1rem);

To

margin: 0 0 .25rem calc(30px + 1rem);

**Comment by sdenec** [comment]
Essentially the same comment as in you other issue^^
