### ISSUE TITLE
Modules with long name underflow weirdly

### ISSUE THREAD

**Issue by mkahvi** [sdenec/tidy-ui_game-settings#53]
Not a huge issue. This is happening only with an experimental module with purposefully long display name and version number (includes date).

![Screenshot 2021-06-09 172946 (2)](https://user-images.githubusercontent.com/8120158/121374264-70aac480-c948-11eb-8b2e-79fd2c6cbc05.png)

It displays "fine" without Tidy UI tho (it doesn't actually, but it's less obvious).

**Comment by GabrielOsvair** [comment]
The same problem here

**Comment by sdenec** [comment]
Should be fixed in the next update!
