### ISSUE TITLE
Filtering Errors

### ISSUE THREAD

**Issue by revilowaldow** [sdenec/tidy-ui_game-settings#54]
https://github.com/BlitzKraig/fvtt-SocketSettings/issues/12#issue-912280836 

When filtering settings with the socket settings module installed, the Sync Button text gets overwritten by the setting description.
See the issue above.

**Comment by sdenec** [comment]
This seems to be resolved? I can't reproduce this on my end.
![working_socketsettings](https://user-images.githubusercontent.com/8881200/127775121-3710e992-7d3c-458d-9fcf-000141c32979.jpg)

**Comment by revilowaldow** [comment]
The error is between "Socket Settings" & "DF Settings Clarity"
