### ISSUE TITLE
[Request] Dark UI mode like for Tidy5e?

### ISSUE THREAD

**Issue by Baxmann** [sdenec/tidy-ui_game-settings#55]
Your Dark UI was nice for 5e, it'd be nice to have it for the whole program.

**Comment by sdenec** [comment]
Nice to hear that you like the dark mode! But to adapt it to the whole foundry UI is a task I don't want to tackle. Have you tried to use another dark mode mod that affects the core ui? I think there was dnd5e dark? That should be compatible with the darkmode of the sheet.
