### ISSUE TITLE
Conflict with Module Sets

### ISSUE THREAD

**Issue by tjlanza** [sdenec/tidy-ui_game-settings#57]
Foundry VTT 0.8.8, Tidy UI 0.1.23, Module Sets 1.0.1

In what I suspect is a CSS collision, Tidy UI and [Module Sets](https://github.com/cswendrowski/FoundryVTT-module-sets/issues/1) do not play well together in one small spot. Tidy UI causes this toggle button to be out of alignment with the rest of the UI elements.

![image](https://user-images.githubusercontent.com/21128724/128612415-7c4017f5-9717-49d5-b347-599c8757b07e.png)

**Comment by sdenec** [comment]
Will be fixed in the next update.
