### ISSUE TITLE
No longer imports saved text lists

### ISSUE THREAD

**Issue by brother-oak** [sdenec/tidy-ui_game-settings#59]
I used to export my active modules list as text and store the list to re-implement later
The latest version exports in a different format that is not recognised any more when importing. It WILL recognise the old text format, but if you export a list as text now, you won't be able to re-import that text list
I know you can now save as JSON, and this may be the intended way to save/load, but this is different from how it used to work, and nothing explains that an exported text list will not be able to be imported any more.

Can it be changed so import will also work with the new version of the text output? Or at least warn the used that exporting as a text list will NOT be able to import it again!

(Foundry 0.8.9, Tidy UI v0.1.24, Windows PC, Self-hosting)

**Comment by sdenec** [comment]
Yeah, from now on you have to save as json and import as json file or - as i figured someone would have created a file with the old format - you still cann copy the old format in. The new format won't allow to recognize the module naes but is a lot more readable if you want to post your module list on discord or similar.

But you have a point that I should make it more clear that you have to save your configuration as json from now on!
