### ISSUE TITLE
Disabled checkboxes are not greyed out

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy-ui_game-settings#67]
My module disables some checkboxes depending on the setting of other checkboxes.  Without Tidy UI enabled, you can easily see which check boxes are enabled and which aren't...

![image](https://user-images.githubusercontent.com/898086/147126337-f01a429e-aff6-49f4-8089-ad057715b75f.png)

However with TidyUI enabled, you cannot tell the difference between an enabled and disabled checkbox.  The dropdown selection is greyed out though...

![image](https://user-images.githubusercontent.com/898086/147126653-ba70faec-98a7-4a52-89f9-f2efe99c0dc4.png)

**Comment by sdenec** [comment]
got you. I didn't apply styling for disabled checkboxes. should be fixed now!
