### ISSUE TITLE
Request to fix some code that's referencing the wrong HTML

### ISSUE THREAD

**Issue by ironmonk88** [sdenec/tidy-ui_game-settings#69]
Would it be possible to make a small alteration to the code?
Line 84 `html.find(".settings-list article.module-wrapper").sort(Ascending_sort).appendTo('.tab[data-tab="modules"] .settings-list');`
could that be changed to
`html.find(".settings-list article.module-wrapper").sort(Ascending_sort).appendTo(active);`

Problem I'm having with my module is I'm altering the HTML, but sending the new HTML to the renderSettingsConfig so that it can get modified by other modules.  The current code ends up modifying the existing HTML rather than the one I want to replace it with.

Thank you.

**Comment by sdenec** [comment]
Sure thing!
