### ISSUE TITLE
Cannot install Tidy UI Game Settings on 0.8.9 Foundry VTT.

### ISSUE THREAD

**Issue by C-S-McFarland** [sdenec/tidy-ui_game-settings#72]
When I attempt to install Tidy UI Game Settings version 0.1.29, I see the following error in my browser:

![Capture](https://user-images.githubusercontent.com/3029853/148235523-fdf86c23-65cb-40b5-bc86-6d0762f1a708.JPG)

I also see this error in the Foundry server logs: 

`FoundryVTT | 2022-01-05 14:35:49 | [warn] Module metadata validation failed for tidy-ui_game-settings: Invalid language code provided which is not supported by Intl.getCanonicalLocales`

**Comment by C-S-McFarland** [comment]
I forked this project, reverted to version 0.1.28 and I was able to install it fine from my fork. So, I suspect something changed in 0.1.29 that broke support for Foundry 0.8.9.

If this is intended, you may want to update the modules.json to report that version 0.1.29 does not support 0.8.x versions of Foundry.

**Comment by sdenec** [comment]
My only suspicion is that v9 interprets the module.json differently thatn previous versions. I put a single "9" in compatibility as requested by many. It is likely that pre v9 this isn't an accepted value and causes issues. Everything else inside the module wasn't touched in a away that ist should affect compatibility. Btw. you don't have to fork the project. I keep all version in the version folder exactly for cases like this.

**Comment by C-S-McFarland** [comment]
The minimum core version is 0.7, and if the current 0.1.29 version won't work in 0.8.x, then perhaps it's time to change that minimumcoreversion to 9 as well?

**Comment by sdenec** [comment]
the thing is I don't see any reason that it shouldn't (apart from the version number thing) but maybe you are right

**Comment by C-S-McFarland** [comment]
You may be right. Perhaps this is the problem? https://github.com/sdenec/tidy-ui_game-settings/blob/master/module.json#L35

I don't think `ja.json` is a valid country code, but I bet `ja` is.

**Comment by sdenec** [comment]
ohhhhh, I totally did not see that. This was a pull request!

**Comment by sdenec** [comment]
I have corrected this entry. Could you maybe try and see if this also solves the installation issue?

**Comment by C-S-McFarland** [comment]
@sdenec Working great with version 0.1.30! Thank you for your efforts and fixing this so quickly!

**Comment by sdenec** [comment]
no, thanks to you! I never would have found this one :)
