### ISSUE TITLE
Manage modules window cut off at bottom

### ISSUE THREAD

**Issue by Weissrolf** [sdenec/tidy-ui_game-settings#74]
TidyUI causes the Manage modules window to be slightly cut off at the bottom of the browser window when it is combined with the "Quick Module Enable module". Happens in Chrome and Firefox.

https://i.imgur.com/I5brrEy.png

Just a few pixels missing at the bottom.

**Comment by vt-tom** [comment]
Same here on v10:
![grafik](https://user-images.githubusercontent.com/80099175/188583801-e2be92b7-0c52-44f7-84ce-2ef81f9b2c6c.png)

**Comment by sdenec** [comment]
should be fixed now.
