### ISSUE TITLE
Blank space in settings when TidyUI is enabled.

### ISSUE THREAD

**Issue by cs96and** [sdenec/tidy-ui_game-settings#75]
They say a picture speaks 1,000 words...

![image](https://user-images.githubusercontent.com/898086/148579039-fd08d859-e250-484b-8192-b86cea35dd98.png)

![image](https://user-images.githubusercontent.com/898086/148578869-5b1838cc-5680-4b9f-b661-fef1139bcd0f.png)

**Comment by struckyCZ** [comment]
Yeah, also this - after the Foundry's yesterday update.
![image](https://user-images.githubusercontent.com/80347865/151308347-4f724395-3fd9-450b-a492-e68ddf01f60b.png)
![image](https://user-images.githubusercontent.com/80347865/151308447-14071d94-c109-4fc8-918c-cb23afa1d54e.png)
The blank space is not present only in the Module Settings.
![image](https://user-images.githubusercontent.com/80347865/151308520-b29e173d-fd43-4aeb-a5db-a3932f8d4bf2.png)

**Comment by vt-tom** [comment]
Same in my Settings with the Das Schwarze Aufge/The Dark Eye (5th) Edition and Foundry Version 9.245.

![grafik](https://user-images.githubusercontent.com/80099175/151345440-c5bcb8c3-fd6c-4296-ac19-f4750418412f.png)

**Comment by M0nk3yy** [comment]
It gets worse if you try and search for a module lol 

![image](https://user-images.githubusercontent.com/66137312/151580354-285f8352-915f-42f1-93be-55fcdb0c2974.png)

**Comment by sdenec** [comment]
The whole window changed a lot with v10 so for now the module leaves it as is. That also means this issue no longer exists. Maybe in time I'll pretty it up again and try to prevent this issue from the get go^^
