### ISSUE TITLE
Tabs broken in last Foundry update 9.245

### ISSUE THREAD

**Issue by Stefouch** [sdenec/tidy-ui_game-settings#77]
The new Foundry 9.245 just broke the tabs with this module (see screenshot below)

No issue if Tidy UI is disabled.

Tested with Tidy UI last version (and no other module activated).

The issue was not in Foundry 9.242

![image](https://user-images.githubusercontent.com/47865544/151705256-0d67539c-4b82-4913-82b5-ffe6e88895ad.png)

**Comment by Stefouch** [comment]
And might be related to https://gitlab.com/foundrynet/foundryvtt/-/issues/6615

**Comment by Stefouch** [comment]
I found the change in `styles.css` : (left 9.242; right 9.245)
This one if for the sheet tabs, but there are similar changes for settings dialogs.
![image](https://user-images.githubusercontent.com/47865544/151707241-041eabe7-b00b-4a35-b49d-047e13f27008.png)

**Comment by jeremyregnerus** [comment]
Is there a temporary fix for this?

**Comment by Rapunzel77** [comment]
Issue #78 suggests to add this
.tabs {
flex: 0 !important;
}
to the custom css mod. And it worked for me

**Comment by sdenec** [comment]
the blank space thin was implemented into the official css. Thnaks for sniffing it out!
