### ISSUE TITLE
Search bar weird behavior

### ISSUE THREAD

**Issue by brunocalado** [sdenec/tidy-ui_game-settings#78]
![image](https://user-images.githubusercontent.com/4999783/151713420-ebb7ba89-731c-4a8d-ab24-0e85d114913d.png)

![image](https://user-images.githubusercontent.com/4999783/151713437-03827e83-593f-4e64-9e91-518c5c998c36.png)

**Comment by r-valyar** [comment]
I second that - all systems are impacts - PF2, D&D, clean installs.

**Comment by bnp800** [comment]
same for pf1

**Comment by winterwulf** [comment]
I have fixed it adding this line in custom css module:

.tabs {
    flex: 0 !important;
}

should fix it until the developer update the mod.

**Comment by vt-tom** [comment]
@winterwulf could you please explain which file you mean?
the tidy-ui_game-settings.css?

**Comment by Darkiller25** [comment]
Worked like a charm! Thanks!

**Comment by Darkiller25** [comment]
@winterwulf Would you have a fix as well, by any chance for this one too?

![image](https://user-images.githubusercontent.com/71094682/153506957-55788df0-c8fe-4d2c-af4e-857883e4617c.png)

**Comment by winterwulf** [comment]
@Darkiller25 send me a msg in discord (search my username in foundry discord)

**Comment by sdenec** [comment]
the blank space thin was implemented into the official css. Thnaks for sniffing it out!
