### ISSUE TITLE
[V10] Module breaks the "Configure Settings" dialog window

### ISSUE THREAD

**Issue by r-valyar** [sdenec/tidy-ui_game-settings#81]
When the module is enabled, the Configure Settings is no longer working, preventing usage of the VTT unless the module is disabled.
![image](https://user-images.githubusercontent.com/63558984/187842575-f3accaaf-7b9d-4a74-8397-fbed42c250a4.png)

**Comment by sdenec** [comment]
There changed a lot in this specific window. The new update adresses this and - for now - leaves this window as is. So this issue should be fixed. Maybe I'll come back to this in time and pretty it up again :)
