### ISSUE TITLE
[v10 - DSA/TDE 5th Edition] Text in Module list is in the UI

### ISSUE THREAD

**Issue by vt-tom** [sdenec/tidy-ui_game-settings#83]
To be clear, this is a problem with the css of the setting, but i thougt the best to start is here. The text above the Modules is directly in the ui on top. As you can see in the screenshot:  
<img width="503" alt="chrome_GnfKTv11ev" src="https://user-images.githubusercontent.com/80099175/188456099-996f3251-f506-49dc-b910-16e9e9dd2e96.png">
and here in german:  
<img width="509" alt="chrome_bNJyXZjgMu" src="https://user-images.githubusercontent.com/80099175/188456137-379ab55b-31a7-44ab-a754-8d7aa53d9b2b.png">

**Comment by sdenec** [comment]
This seems to be more a DSA-related issue than a module issue. I didn't change any css and in the regular foundry theme the items just stack on top of each other. The DSA-Theme seems to have a fixed header height resulting in an overlap when the buttons come in ... anyhow, I'll see if I can adress it on my end.

**Comment by sdenec** [comment]
Should be fixed. The DSA Theme had changed the height of the info text but could easily be reset. Let me know if it looks alright now! 

Mögen die Zwölfe mit euch sein!

**Comment by sdenec** [comment]
hm, should be 0.1.5! Would you try again. Maybe uninstall and reinstall?

**Comment by vt-tom** [comment]
With version 0.15 it works. Thank you very much 😊
