### ISSUE TITLE
[v10] deactive every module except tidy - deactivates also tidy

### ISSUE THREAD

**Issue by vt-tom** [sdenec/tidy-ui_game-settings#84]
The Button "deactive every module except tidy" - deactivates also tidy ui

![grafik](https://user-images.githubusercontent.com/80099175/188586204-0169b5e8-4842-4dd3-ac34-cda5ab782f0f.png)

**Comment by sdenec** [comment]
Check if you are o 0.1.5
Unchecking all leaves tidy ui enabled.
