### ISSUE TITLE
Enabling 'Always Activate Settings Tab' Removes all visible options

### ISSUE THREAD

**Issue by iameternity** [sdenec/tidy-ui_game-settings#86]
Title. As of V10, checking this box makes it so that the Config Settings menu is blank. Hitting 'Reset Defaults' does not fix this issue

**Comment by iameternity** [comment]
Found the problem -- Forge has your latest release as 0.1.33 and not 0.1.5 so the core of the module is compatible and it loads but not anything else

**Comment by sdenec** [comment]
hm, maybe I just have to relase a new version number

**Comment by sdenec** [comment]
should be fixed now.
