### ISSUE TITLE
Incorrect version releases

### ISSUE THREAD

**Issue by kakaroto** [sdenec/tidy-ui_game-settings#87]
Hi,
It was brought to my attention that your latest module releases appear as not available on the Bazaar (too old), and it turned out to be because you've released `0.1.4` and `0.1.5` which are lower versions than `0.1.33` (33 > 5). 
Considering that your previous releases were using `0.1.20` and `0.1.30`, you probably meant to do a `0.1.40` and `0.1.50`  release instead of `0.1.4` and `0.1.5`, and made the wrong version by mistake.
If you could please release a new update with the double digit patch version in the semantic versioning, that'd be great.
Thanks!

**Comment by sdenec** [comment]
whoops. Didn't think about that. Since I had another update due I changed it to 0.1.51 - I hope that'll do it!

**Comment by kakaroto** [comment]
Thanks for the quick fix! That did it! 👍 
Note: Your changelog says "Forge Version fix" but really, it's "semantic versioning fix" 😜 I'm not entirely sure, but I think it also would have affected self-hosted users since Foundry would see it as a downgrade and would not do the update when they "check for updates"

**Comment by sdenec** [comment]
Hm, that might be true, though I didn't notice that. Sorry if it appears that I blame Forge for it, wasn't my intention^^ Totally true that I should keep to my own sematics!
