### ISSUE TITLE
Tidy-UI 0.1.5 keeps updating

### ISSUE THREAD

**Issue by Kapharnaum** [sdenec/tidy-ui_game-settings#9]
Hello,
When updating my modules multiple times, Tidy-UI keeps saying it upgraded to 0.1.5

**Comment by sdenec** [comment]
Sorry, but I can't replicate the issue. Mine stays at the current version without redownloading. Do you use a fresh install? Could you maybe try to uninstall and reinstall the module to check if the issue persists? All version numbers are up to date so it should work witout issues.

**Comment by Kapharnaum** [comment]
I uninstalled / reinstalled and it worked. The name changed btw. Went from fvtt - ui... to Tidy-ui.
Thx.
